name: Publish Packages
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup build cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: libreforge-dev-${{ steps.vars.outputs.sha_short }}
          path: build/libs
